export const INFERENCE_CLIENT_INITIALIZATION_TIMEOUT_MS = 20_000
export const TITLE_SOURCE_MAX_CHARACTERS = 12_000
export const CHAT_TOKEN_RATE_LIMIT_FALLBACK_MS = 60_000
export const CHAT_TOKEN_MAX_COOLDOWN_MS = 60 * 60 * 1000
export const MILLISECONDS_PER_SECOND = 1000

export const CHAT_TOKEN_HTTP_STATUS = {
  UNAUTHORIZED: 401,
  SUBSCRIPTION_REQUIRED: 402,
  REQUEST_TIMEOUT: 408,
  INVALID_RESPONSE: 502,
} as const
