export const INFERENCE_CLIENT_INITIALIZATION_TIMEOUT_MS = 20_000
export const TITLE_SOURCE_MAX_CHARACTERS = 12_000

export const CHAT_TOKEN_HTTP_STATUS = {
  UNAUTHORIZED: 401,
  SUBSCRIPTION_REQUIRED: 402,
  INVALID_RESPONSE: 502,
} as const
